name: Auto Merge PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge PR
        run: |
          PR_NUMBER=$(jq --raw-output .number "$GITHUB_EVENT_PATH")
          echo "Merging PR #$PR_NUMBER"
          
          curl --location --request PUT \
          "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge" \
          --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          --header "Content-Type: application/json" \
          --data '{ "commit_title": "Automatically merged", "merge_method": "merge" }'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
