name: Auto Merge PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge PR
        uses: actions/github-script@v5.1.0
        with:
          script: |
            const { repo, pull_request } = context;
            const mergeParams = {
              owner: repo.owner,
              repo: repo.repo,
              pull_number: pull_request.number,
              merge_method: "merge",
              commit_title: `Automatically merged PR #${pull_request.number}`
            };
            await github.rest.pulls.merge(mergeParams);
          github-token: ${{ secrets.GITHUB_TOKEN }}
