name: Auto Merge PR

on:
  pull_request:
    types:
      - opened
      - synchronize
  pull_request_review:
    types:
      - submitted

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automerge,!work in progress"
          MERGE_METHOD: "merge"
          MERGE_COMMIT_MESSAGE: "Automatic merge of PR {pullRequest.number}: {pullRequest.title}"
          MERGE_FORKS: "false"
          UPDATE_LABELS: "automerge,!work in progress"
          UPDATE_METHOD: "merge"
